### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by nicodinh**
typo :rofl:

### CODE REVIEW

**Comment by givingwu** [comment]
Thanks.

**Comment by givingwu** [comment]
Hi, sir, thank u again. if u do not pull this request, may i never know this typo error of mine. So funny.....

**Comment by nicodinh** [comment]
You're welcome. :smile:

**Comment by givingwu** [comment]
this Pull Request was the first PR in my programmer life except daily work. I love open source work. That is so nice!!!

**Pull request merged**
